geometry_msgs/PoseStamped gripper_to_plug
geometry_msgs/PoseStamped base_to_outlet
geometry_msgs/PoseStamped initial_plug_pose
float64 insertion_depth
float64 wiggle_amplitude
duration wiggle_period
duration timeout
float64 arbort_threshold

---
---
