vision_plug_detection:
  square_size: 0.006
  board_width: 4
  board_height: 5
  plug_position_x: 0.021
  plug_position_y: 0.037
  plug_position_z: 0.0285
  plug_orientation_x: 0.5
  plug_orientation_y: 0.5
  plug_orientation_z: -0.5
  plug_orientation_w: -0.5

