# List of outlet approach poses
# These are all poses of the base_link in the map frame
outlet_approach_poses:
  wim:
    position: [20.565, 25.973, 0.051]
    orientation: [-0.008, -0.004, 0.953, 0.302]
  phasespace:
    position: [19.457, 16.099, 0.051]
    orientation: [-0.003, -0.002, 0.408, 0.913]
