# List of outlet approach poses
# These are all poses of the base_link in the map frame
outlet_approach_poses:
  wim:
    position: [20.565, 25.973, 0.051]
    orientation: [-0.008, -0.004, 0.953, 0.302]
  phasespace:
    position: [19.457, 16.099, 0.051]
    orientation: [-0.003, -0.002, 0.408, 0.913]
  outlet_I_31: 
    position: [20.714, 23.834, 0.048]
    orientation: [0.001, -0.001, 0.978, 0.208]